//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Research_Gate_1._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paper
    {
        public Paper()
        {
            this.Comments = new HashSet<Comment>();
            this.Reactions = new HashSet<Reaction>();
            this.Authors = new HashSet<Author>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public byte[] PaperFile { get; set; }
        public int PublichYear { get; set; }
        public string Category { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Reaction> Reactions { get; set; }
        public virtual ICollection<Author> Authors { get; set; }
    }
}
